@startuml
skinparam monochrome true

actor Utilisateur

participant "Laby:Labyrinthe" as Laby
participant "p:Perso" as P
participant "m:Monstre" as M

Utilisateur -> Laby: deplacerPerso(String)
activate Laby
Laby -> P: getX()
activate P
Laby <-- P: X
Laby -> P: getY()
Laby <-- P: Y
deactivate P
Laby -> M: getX()
activate M
Laby <-- M: X
Laby -> M: getY()
Laby <-- M: Y
deactivate M
Laby -> Laby: getSuivant(x,y,String)
alt !getMonstrePresent(x,y)
    Laby -> P: setX()
        activate P
        Laby <-- P:
        Laby -> P: setY()
        Laby <-- P:
        deactivate P
end
Laby --> Utilisateur
deactivate Laby


@enduml
