@startuml
skinparam monochrome true

actor Utilisateur

participant "Laby:Labyrinthe" as Laby
participant "p:Perso" as P

Utilisateur -> Laby: deplacerPerso(String)
activate Laby
Laby -> P: getX()
activate P
Laby <- P: X
Laby -> P: getY()
Laby <- P: Y
deactivate P
Laby -> Laby: getSuivant(x,y,String)
Laby --> Utilisateur
deactivate Laby

@enduml
