@startuml
skinparam monochrome true

actor Utilisateur

participant "Laby:Labyrinthe" as Laby
participant "M:Monstre" as M

Utilisateur -> Laby: deplacerMonstre(i:Int)
activate Laby
Laby -> Laby: getProchaineAction(i):String
activate Laby
Laby --> Laby: action
deactivate Laby
Laby -> M: getX():Int
activate M
Laby <-- M: x
Laby -> M: getY():Int
Laby <-- M: y
deactivate M
Laby -> Laby: getSuivant(x,y,action)
alt !getMonstrePresent(x,y)
    Laby -> M: setX()
        activate M
        Laby <-- M:
        Laby -> M: setY()
        Laby <-- M:
        deactivate M
end
Laby --> Utilisateur
deactivate Laby

@enduml
